In [35]:
import numpy as np
from sympy import *
from sympy.matrices import *
from scipy.linalg import solve_lyapunov

In [38]:
g = 0.5
H = np.matrix([[1,0],[0,2]])
A = np.matrix([[0,1],[-1,-2*g]])
print np.linalg.eig(A)
BWB = np.matrix([[-1,0],[0,-8]])
Q_numeric = solve_lyapunov(A,BWB)
Q_symbolic = np.matrix([[g + 9/(4.0*g),-1/2.0],[-1/2.0,9/(4.0*g)]])

print "Q numeric is"
print Q_numeric
print "Q symbolic is"
print Q_symbolic




(array([-0.5+0.8660254j, -0.5-0.8660254j]), matrix([[ 0.70710678+0.j        ,  0.70710678-0.j        ],
        [-0.35355339+0.61237244j, -0.35355339-0.61237244j]]))
Q numeric is
[[ 5.  -0.5]
 [-0.5  4.5]]
Q symbolic is
[[ 5.  -0.5]
 [-0.5  4.5]]


In [34]:
gamma = Symbol('gamma')
a, b, c, d = symbols('a b c d')
A = Matrix([[0,1],[-1,-2*gamma]])
Q = Matrix([[a,b],[c,d]])
print A
print Q
T = A*Q + Q*A.transpose()
print T
C = Matrix([[0,1,1,0],[-1, -2*gamma, 0,1],[-1, 0, -2*gamma, 1],[0, -1, -1, -4*gamma]])
print C
BW = Matrix([[-1],[0],[0],[-8]])
print BW
SS = C.inv()*BW
print SS

Matrix([[0, 1], [-1, -2*gamma]])
Matrix([[a, b], [c, d]])
Matrix([[b + c, -a - 2*b*gamma + d], [-a - 2*c*gamma + d, -b - c - 4*d*gamma]])
Matrix([[0, 1, 1, 0], [-1, -2*gamma, 0, 1], [-1, 0, -2*gamma, 1], [0, -1, -1, -4*gamma]])
Matrix([[-1], [0], [0], [-8]])
Matrix([[gamma + 9/(4*gamma)], [-1/2], [-1/2], [9/(4*gamma)]])
